# Generated by Django 3.2 on 2021-04-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='measure',
            field=models.CharField(choices=[('KG', 'Kilograms'), ('UN', 'Units')], max_length=2),
        ),
    ]
